[project]
name = "finance-mobile"
version = "1.0.0"
description = "Personal finance manager"
requires-python = ">=3.10"
dependencies = [
  "flet==1.0.3",
  "flet-charts==1.0.3",
]

[tool.flet]
org = "com.hkabo"
product = "Finance Manager"

[tool.flet.flutter.pubspec.dependency_overrides]
jni = "1.1.0"
