name: finance_mobile
description: برنامه مدیریت مالی موبایل
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flet: ^0.24.1

dependency_overrides:
  shared_preferences_android: 2.3.2
  wakelock_plus: 1.2.8